sudo: required
services:
- docker
install: true
script: "./test/run.sh"
branches:
  only:
  - master
  - no-default-service
notifications:
  slack:
    secure: rMSgegC+kHNIDVHggLgyWVJneNIqs82KPfnqdaGW6uuXQ3zcMMhO+Q58c1x0vPs/QhLXjRrTGPQfkqHxrWM1YraxJAdugvICN3yGbLulD+PP2w8RPee14zfEHz+X7+Tfcc+EUKsezkPqnxTINCIAnES0kka3ngGiGUSMJzfmXsAyaG8lGP50hj1iHNUVfemzoY4pjMSuEOEevrJJlT4+jcHYi2fXjS2GKEnBysIdqB6uVuAgKBxfNCqkMjbVmSOeui/5YkYGPIw2L/sX1c9r2hc5opXhTCJmLBylLPotOBzA7lf7xE+my6YZDJq+HS7ElyuTaCG40NaciQZYJ8IrZ2giaYkJ+kUQsi6FVOb5246EsBq+h8JpkUdFQ5VVkkd3Ohx3A8dOMl6n86vhSN6RXYnbLwRbbB4ODC0XvajtEq2AupP3X3zgqcxDG7WM3IruKQ0SEDjcHqbuEM6otJwPtgqJeiFYq+51fjteX/8n0VHZZF3XmwL2D1h+JvXn4R4RQfIrnZKb6m5JAeB3QGWNdQRYQIjcJXiKF1VYTJoSl2QWElJO3lKttCaMXGbMSDIrGxSM1GKF0qN78PmXPsH1MIaicRfpGge7X58llKNbbVABBQh3E+p6w4G7kTOJCoEcildO0m9Vl2sUP+iCiCyaREcHT5WX22P2fXj6sQOJt5U=
  on_success: change
  email: false
