---
name: Test
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  publish:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - run: ./test/run.sh
